services:
  pipeline:
    build:
      context: ./qanary_pipeline-template
      args:
        JAR_FILE: ${PIPELINE_NAME}-${PIPELINE_VERSION}.jar
    environment:
      - "QANARY_QUESTIONS_DIRECTORY=/qanary-questions"
    volumes:
      - "qanary_questions:/qanary-questions"
    image: ${PIPELINE_IMAGE}:${PIPELINE_VERSION}
    ports:
      - "${PIPELINE_PORT}:8080"
volumes:
  qanary_questions:
