PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT {
GRAPH ?graph {
        ?newAnnotation rdf:type qa:AnnotationOfLog .
        ?newAnnotation oa:hasBody ?body .
        ?newAnnotation oa:annotatedAt ?time .
        ?newAnnotation oa:annotatedBy ?component .
        ?newAnnotation oa:hasTarget ?questionID .
    }
}
WHERE {
    BIND (IRI(CONCAT("urn:qanary:", STR(RAND()))) AS ?newAnnotation) .
    BIND (now() as ?time) .
}