PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT { 
GRAPH ?graph  {
        ?newTypeAnnotation rdf:type qa:AnnotationOfAnswerType .
        ?newTypeAnnotation oa:hasTarget ?targetQuestion .
        ?newTypeAnnotation oa:hasBody ?annotationOfAnswerType .
        ?newTypeAnnotation qa:score ?confidence .
        ?newTypeAnnotation oa:annotatedAt ?time .
        ?newTypeAnnotation oa:annotatedBy ?application . 

        ?answerType rdf:type qa:AnswerType .
        ?answerType rdf:value ?answerDataType .
    }
}
WHERE {
    BIND (IRI(CONCAT("urn:qanary:annotation:answer:type:", STR(RAND()))) AS ?newTypeAnnotation) .
    BIND (IRI(CONCAT("urn:qanary:answer:type:", STR(RAND()))) AS ?answerType) .
    BIND (now() as ?time) . 
}
