PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
	GRAPH ?graph {
		?annotationId a qa:AnnotationOfQuestionTranslation ;
			oa:hasTarget ?hasTarget ;
			oa:hasBody ?hasBody ;
			oa:annotatedBy ?annotatedBy ;
			oa:annotatedAt ?annotatedAt .
	}
} WHERE {
	BIND (IRI(str(RAND())) AS ?annotationId) .
	BIND(now() as ?annotatedAt) .
}
