PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT { 
GRAPH ?graph  {
        ?newAnnotation rdf:type qa:AnnotationOfAnswerSPARQL .
        ?newAnnotation oa:hasTarget ?targetQuestion .
        ?newAnnotation oa:hasBody ?selectQueryThatShouldComputeTheAnswer .
        ?newAnnotation qa:score ?confidence .
        ?newAnnotation oa:annotatedAt ?time .
        ?newAnnotation oa:annotatedBy ?application . 
    }
}
WHERE {
    BIND (IRI(CONCAT("urn:qanary:annotation:answer:sparql:", STR(RAND()))) AS ?newAnnotation) .
    BIND (now() as ?time) . 
}
