PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT *
FROM ?graph
WHERE { 
        ?annotationId rdf:type qa:AnnotationOfAnswerSPARQL .
        ?annotationId oa:hasTarget ?hasTarget ;
        oa:hasBody ?hasBody .
        OPTIONAL {
                ?annotationId qa:score ?score .
        }
        OPTIONAL {
                ?annotationId qa:index ?index .
        }
        ?annotationId oa:annotatedAt ?annotatedAt ;
        oa:annotatedBy ?annotatedBy . 
}
