PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
 
SELECT DISTINCT ?graph ?p ?o 
WHERE { 
    GRAPH ?graph {
        ?questionId owl:sameAs <urn:qanary:currentQuestion> .
    }
}