PREFIX  qa:   <http://www.wdaqua.eu/qa#>
PREFIX  oa:   <http://www.w3.org/ns/openannotation/core/>
PREFIX  dbr:  <http://dbpedia.org/resource/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
FROM ?graph
WHERE {
    ?annotationId rdf:type qa:AnnotationOfTextAnswerJson .
    ?annotationId oa:hasTarget ?hasTarget
    ?annotationId oa:hasBody ?hasBody .
    ?annotationId oa:annotatedAt ?annotatedAt .
    ?annotationId oa:annotatedBy ?annotatedBy .
    ?hasBody rdf:type qa:AnswerJson .
    ?hasBody rdf:value ?value .
    qa:AnswerJson rdfs:subClassOf qa:Answer .
    }
