PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>

SELECT *
FROM ?graph
WHERE {
    ?annotationId rdf:type qa:AnnotationOfSpotInstance.
    ?annotationId oa:hasTarget [
                    a oa:SpecificResource;
                      oa:hasSource ?hasSource;
                      oa:hasSelector [
                            a oa:TextPositionSelector;
                            oa:start ?start;
                            oa:end ?end
                      ]
    ].
    ?annotationId oa:annotatedAt ?annotatedAt ;
                  oa:annotatedBy ?annotatedBy .
}
