Prefix qa: <http://www.wdaqua.eu/qa#>
Prefix oa: <http://www.w3.org/ns/openannotation/core/>
Prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT *
FROM ?graph
WHERE {
?annotationId a qa:AnnotationOfQuestionLanguage .
?annotationId oa:hasTarget ?hasTarget ; 
  oa:hasBody ?hasBody ;
  oa:annotatedBy ?annotatedBy ;
  oa:annotatedAt ?annotatedAt .
  }
