PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * 
FROM ?graph
WHERE { 
		?newAnnotation rdf:type qa:AnnotationOfAnswerSPARQL .
		?newAnnotation oa:hasTarget ?targetQuestion .
		?newAnnotation oa:hasBody ?selectQueryThatShouldComputeTheAnswer .
		?newAnnotation qa:index ?index .
		?newAnnotation oa:annotatedAt ?time .

		{
		    SELECT ?time 
		    WHERE {
	    		?newAnnotation rdf:type qa:AnnotationOfAnswerSPARQL .
		    	?newAnnotation oa:annotatedAt ?time .
		    } 
		    ORDER BY DESC(?time) 
		    LIMIT 2
		}

		?newAnnotation oa:annotatedBy ?application . 
	}
ORDER BY ASC(?index) 
LIMIT 1
