PREFIX qa: <http://www.wdaqua.eu/qa#>
PREFIX oa: <http://www.w3.org/ns/openannotation/core/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT {
GRAPH ?graph {
    ?a  rdf:type    qa:AnnotationOfLogMethod ;
        qa:className    ?class ;
        qa:methodName   ?method ;
        qa:input    ?input ;
        qa:output   ?output ;
        oa:annotatedAt  ?time .
}}
WHERE {
    BIND (IRI(CONCAT("urn:qanary:logging:method:", STR(RAND()))) AS ?a) .
    BIND (now() as ?time)
}